I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 417, in script
    $ clears += 1
  File "game/script.rpy", line 417, in <module>
    $ clears += 1
NameError: name 'clears' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 417, in script
    $ clears += 1
  File "C:\Users\seung\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\seung\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 417, in <module>
    $ clears += 1
NameError: name 'clears' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Project_Horror 1.0
Sun Apr  6 22:34:55 2025
